### ISSUE TITLE
What's the state of this project?

### ISSUE THREAD

**Issue by DaRochaRomain** [HangfireIO/Hangfire.InMemory#1]
Hello, I'm currently using this [package](https://github.com/perrich/Hangfire.MemoryStorage) as a memory storage for hangfire, and I wonder how this projet is going? Is it abandonned? Is it worth switching to this one?

**Comment by odinserj** [comment]
Hello, it's alive, fully supported and I have some evidences it's more stable than the referenced project, especially with complex features like batches or throttlers. I don't bump its version to 1.0, because want to implement better handling of `OutOfMemoryException` first, and this is the only reason. Also there are a lot of unit tests implemented – https://ci.appveyor.com/project/odinserj/hangfire-inmemory/build/tests.

**Comment by DaRochaRomain** [comment]
Thanks for your quick answer. I'll start switching to this one then.
